export enum Role {
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  ADMIN = 'ADMIN',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  MORE_INFO_REQUIRED = 'MORE_INFO_REQUIRED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum IssueType {
  FRAUD = 'FRAUD',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  LATE_PAYMENT = 'LATE_PAYMENT',
  FAKE_ORDER = 'FAKE_ORDER',
  ORDER_CANCELLATION = 'ORDER_CANCELLATION',
  FINANCIAL_LOSS = 'FINANCIAL_LOSS',
  TIME_LOSS = 'TIME_LOSS',
  MISLEADING_INFO = 'MISLEADING_INFO',
  OTHER = 'OTHER',
}
